name: Python Package Test
on: workflow_dispatch

jobs:
  test_and_run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run fake unit tests
      run: |
        echo "Running tests..."
        sleep 5
        echo "All tests passed!"

    # Запуск удаленного доступа
    - name: Setup Remote Connection Session
      uses: mxschmitt/action-tmate@v3
